sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t spglab/wyk7 -f Dockerfile.dev2 .

script:
  - docker run -e CI=true spglab/wyk7 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "pfswcho-zadanie-2"
  env: "Pfswchozadanie2-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-212058688361"
  bucket_path: "pfswcho-zadanie-2"
  edge: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
